version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/gradle
  gradle: circleci/gradle@3.0.0

executors:
  openjdk17:
    docker:
      # OpenJDK convenience image: https://circleci.com/developer/images/image/cimg/openjdk
      - image: cimg/openjdk:17.0

jobs:
  test_sub_project:
    executor:
      name: openjdk17
    steps:
      - checkout
      - run:
          command: gradlew :src:server:test

workflows:
  build-and-test:
    jobs:
      - test_sub_project
