version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/gradle
  gradle: circleci/gradle@3.0.0

executors:
  openjdk17:
    docker:
      # OpenJDK convenience image: https://circleci.com/developer/images/image/cimg/openjdk
      - image: cimg/openjdk:17.0

workflows:
  build-and-test:
    jobs:
      - gradle/test:
          executor: openjdk17
